version: '2'
services:
  db:
    build: postgres_docker_setup
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
  q-hiring-hapi:
    build: ../q-hiring-hapi
    volumes:
      - "../q-hiring-hapi:/q-hiring-hapi/"
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
  q-hiring-abstraction:
    build: ../Q-hiring-abstraction
    volumes:
      - "../Q-hiring-abstraction:/Q-hiring-abstraction/"
    ports:
    - "3002:3002"
    links:
    - db
    depends_on:
    - db
    environment:
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
  q-hiring-redux:
    build: ../q-hiring-redux
    volumes:
      - "../q-hiring-redux:/q-hiring-redux/"
    ports:
    - "8080:8080"